### ISSUE TITLE
tutorial орчуулга

### ISSUE THREAD

**Issue by dulmandakh** [react-mongolia/react-native#1]
[tutorial.docx](https://github.com/react-mongolia/react-native/files/3120957/tutorial.docx) байгаа текстийг [tutorial.md](docs/tutorial.md) нэгтгээд pull request үүсгэх хэрэгтэй байна.

**Comment by telmen** [comment]
assign me @dulmandakh

**Comment by dulmandakh** [comment]
@telmen member invite явуулсан, дараа нь assign хийж болох юм байна
