### ISSUE TITLE
props орчуулга нэгтгэх

### ISSUE THREAD

**Issue by dulmandakh** [react-mongolia/react-native#2]
[props.docx](https://github.com/react-mongolia/react-native/files/3120975/props.docx) энд байгаа текстийг [props.md](docs/props.md) рүү нэгтгээд pull request үүсгэх хэрэгтэй байна

**Comment by telmen** [comment]
assign me @dulmandakh

**Comment by dulmandakh** [comment]
@telmen хэр явж байна даа?

**Comment by telmen** [comment]
@dulmandakh Өнөөдөртөө PR явуулна.
