### ISSUE TITLE
getting started нэгтгэх

### ISSUE THREAD

**Issue by dulmandakh** [react-mongolia/react-native#4]
[getting-started.txt](https://github.com/react-mongolia/react-native/files/3120985/getting-started.txt) энд байгаа орчуулсан текстийг [getting-started.md](docs/getting-started.md) нэгтгээд pull request үүсгэх хэрэгтэй байна

**Comment by telmen** [comment]
Оройн мэнд над руу assign хийнэ үү. Баярлалаа. @dulmandakh
