### ISSUE TITLE
Орчуулга хийгдэх докын жагсаалт

### ISSUE THREAD

**Issue by telmen** [react-mongolia/react-native#5]
[Уг](https://github.com/reactjs/mn.reactjs.org/issues/1) ишшүтэй төстэй орчуулах докуудын жагсаалт гаргах. Энэ ишшүг засварлаад явна гэж бодож байна.

**Comment by dulmandakh** [comment]
Заавал assign хийгээгүй ч гэсэн шууд хийгээд явж болно шүү. Дуусаад PR
үүсгээрэй 👍

>
